# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-21 20:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('game_type', models.CharField(choices=[('single', 'Einzel'), ('men_double', 'Herrendoppel'), ('women_double', 'Frauendoppel'), ('mixed', 'Mixed')], max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_time', models.DateTimeField()),
                ('create_time', models.DateTimeField(auto_now=True)),
                ('canceled', models.BooleanField(default=False)),
                ('games', models.ManyToManyField(to='ticker.Game')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prename', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('birth_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canceled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('associated_club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Club')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rules',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Set',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('set_number', models.IntegerField(default=1)),
                ('points_team_a', models.ManyToManyField(related_name='points_team_a', to='ticker.Point')),
                ('points_team_b', models.ManyToManyField(related_name='points_team_b', to='ticker.Point')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=255)),
                ('players', models.ManyToManyField(to='ticker.Player')),
            ],
        ),
        migrations.CreateModel(
            name='TeamPlayerAssociation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_association', models.DateField()),
                ('end_association', models.DateField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Player')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Team')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='rule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Rules'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_a', to='ticker.Team'),
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_b', to='ticker.Team'),
        ),
        migrations.AddField(
            model_name='league',
            name='matches',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Match'),
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Team'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_a',
            field=models.ManyToManyField(related_name='player_a', to='ticker.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='player_b',
            field=models.ManyToManyField(related_name='player_b', to='ticker.Player'),
        ),
        migrations.AddField(
            model_name='game',
            name='sets',
            field=models.ManyToManyField(to='ticker.Set'),
        ),
    ]
