# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 12:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0002_auto_20160822_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='league',
            name='matches',
        ),
        migrations.AddField(
            model_name='league',
            name='matches',
            field=models.ManyToManyField(to='ticker.Match'),
        ),
        migrations.RemoveField(
            model_name='league',
            name='teams',
        ),
        migrations.AddField(
            model_name='league',
            name='teams',
            field=models.ManyToManyField(to='ticker.Team'),
        ),
        migrations.AlterField(
            model_name='point',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 12, 4, 46, 546990, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='season',
            name='leagues',
            field=models.ManyToManyField(to='ticker.League'),
        ),
    ]
