# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-22 12:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0003_auto_20160822_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='sex',
            field=models.CharField(choices=[('female', 'Weiblich'), ('male', 'Maennlich')], default='female', max_length=32),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='point',
            name='create_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 22, 12, 28, 17, 927270, tzinfo=utc)),
        ),
    ]
