# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 09:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0004_auto_20160822_1428'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='season',
        #     name='leagues',
        # ),
        migrations.AddField(
            model_name='league',
            name='associated_season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticker.Season'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='season',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 9, 57, 40, 931572, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 9, 57, 40, 931572, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='team',
            name='parent_club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticker.Club'),
        ),
        migrations.AlterField(
            model_name='match',
            name='games',
            field=models.ManyToManyField(blank=True, null=True, to='ticker.Game'),
        ),
        migrations.AlterField(
            model_name='point',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
