# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 13:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0007_auto_20160826_1558'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='season',
        #     name='leagues',
        # ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 13, 59, 26, 230847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 13, 59, 26, 230847, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='team',
            name='fields',
            field=models.ManyToManyField(blank=True, to='ticker.Field'),
        ),
        migrations.AlterField(
            model_name='team',
            name='players',
            field=models.ManyToManyField(blank=True, to='ticker.Player'),
        ),
    ]
