# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-26 16:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0008_auto_20160826_1559'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Field',
            new_name='PlayingField',
        ),
        # migrations.RemoveField(
        #     model_name='season',
        #     name='leagues',
        # ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 16, 31, 0, 930207, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 26, 16, 31, 0, 930207, tzinfo=utc)),
        ),
    ]
