# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-08-29 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0011_auto_20160827_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchResponsibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_taken_responsibility', models.DateTimeField(auto_now_add=True)),
                ('time_revoked_responsibilty', models.DateTimeField(default=None)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='season',
            name='leagues',
        ),
        migrations.AlterField(
            model_name='match',
            name='games',
            field=models.ManyToManyField(blank=True, to='ticker.Game'),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 16, 5, 48, 562183, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 8, 29, 16, 5, 48, 562183, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='matchresponsibility',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Match'),
        ),
        migrations.AddField(
            model_name='matchresponsibility',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Profile'),
        ),
    ]
