# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-02 17:30
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticker', '0012_auto_20160829_1805'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresentationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=32)),
                ('is_used', models.BooleanField(default=False)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('usage_time', models.DateTimeField(blank=True, null=True)),
                ('last_action', models.DateTimeField(blank=True, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.PlayingField')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 17, 30, 18, 417379, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 2, 17, 30, 18, 417379, tzinfo=utc)),
        ),
    ]
