# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 20:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0014_auto_20160903_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('displayed', models.BooleanField(default=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Team')),
            ],
        ),
        migrations.CreateModel(
            name='PresentationSlideTeam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_number', models.IntegerField()),
                ('slide_visible', models.BooleanField(default=True)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Presentation')),
            ],
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content_type', models.CharField(choices=[('score', 'Score'), ('advertisement_photo', 'Werbung (Foto)'), ('advertisement_video', 'Werbung (Video)'), ('next_games', 'Naechsten Spiele'), ('next_home_games', 'Naeachsten Heimspiele')], max_length=255)),
                ('content_path', models.TextField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Club')),
            ],
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 20, 47, 22, 298493, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 9, 10, 20, 47, 22, 298493, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='presentationslideteam',
            name='slide',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticker.Slide'),
        ),
    ]
