# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-20 15:29
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0016_bup_presses'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='test_game',
            field=models.BooleanField(default=False),
        ),
    ]
