# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-30 11:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0017_auto_20171020_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='league_key',
            field=models.CharField(default='', max_length=255),
        ),
    ]
