# Generated by Django 3.1.2 on 2020-10-08 07:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('ticker', '0018_auto_20171030_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='cached_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='match',
            name='cached_scorestr',
            field=models.CharField(default='0:0', max_length=32),
        ),
        migrations.AlterField(
            model_name='season',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 7, 38, 49, 545571, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='season',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 7, 38, 49, 545552, tzinfo=utc)),
        ),
    ]
